[package]
name = "election-compass-scraper"
version = "1.0.4"
edition = "2024"

[dependencies]
futures = "0.3.31"
rand = "0.9.2"
thirtyfour = "0.36.1"
tokio = { version = "1.48.0", features = ["full"] }
